### PR TITLE
Issue #44: Quick hack that uses a -D parameter

### PR DESCRIPTION
**Pull request by kgibm**
To use, run with `-Dde.ibm.issw.requestmetrics.Configuration.root_details_find_unique_uris=true`

### CODE REVIEW

**Comment by skliche** [comment]
Ah cool. I had a look at it yesterday and could not figure it out why the build fails. Could you pls provide some sample data under src/test/resources/metricsScenarios/ 
Our test coverage is currently poor, but I'd like to collect use-cases that we can use to validate the parser.

Thx for your contribution ;)

**Comment by kgibm** [comment]
@skliche Yes, `putIfAbsent` was only added in Java 8, but the Travis build uses Java 7, so I just manually did the `get`/`put`.

I added the log file I was using from the customer, although I scrubbed it first with this `bash` command (various filters had customer names so I just replaced everything just in case):

    grep PMRM SystemOut.log | sed 's/detail=\/[^ ]\+ /detail=\/rest /g' \
        | sed 's/detail=[^\/][^ ]\+ /detail=DUMMY_DETAIL /g' > SystemOut_customer_test_rest.log

**Comment by skliche** [comment]
Ah I see. We stick to older Java versions, since our customers quite often do not have J8 runtimes.

**Comment by kgibm** [comment]
Thanks!

**Pull request merged**
